---
title: "Alpha Test Analysis"
date: "`r format(Sys.time(), '%B %d, %Y')`"
author: "James Petrie"
output:
  html_notebook: default
  pdf_document: default
---
```{r echo=TRUE}
require(data.table)
require(rjson)
require(plyr)
require(stringr)
require(ggplot2)
require(readxl)
require(coefplot)
```

```{r}
processExposures <- function(file){
  exposures <- fromJSON(file=file)
  
  if("possibleExposures" %in% names(exposures)){
    exposures = exposures$possibleExposures
  }

  thresholds = sort(unique(unlist(llply(exposures, function(x){
    return(x$attenuationDurationThresholds)
  }))))

  dt = rbindlist(llply(exposures, function(x){
    newDt = data.table(TimeDetected = x$timeDetected,
                       MinThresh = x$attenuationDurationThresholds[[1]],
                       MaxThresh = x$attenuationDurationThresholds[[2]],
                       Duration = x$attenuationDurations[[2]]
    )
    if(x$attenuationDurationThresholds[[1]] == min(thresholds)){
      minDt = data.table(TimeDetected = x$timeDetected,
                         MinThresh = 0,
                         MaxThresh = x$attenuationDurationThresholds[[1]],
                         Duration = x$attenuationDurations[[1]]
      )
      newDt = rbind(minDt, newDt)
    }
    if(x$attenuationDurationThresholds[[2]] == max(thresholds)){
      maxDt = data.table(TimeDetected = x$timeDetected,
                         MinThresh = x$attenuationDurationThresholds[[2]],
                         MaxThresh = 128,
                         Duration = x$attenuationDurations[[3]]
      )
      newDt = rbind(newDt, maxDt)
    }

    return(newDt)
  }))

  return(dt)
}


```

```{r}
processScenarios <- function(scenarioFile){
  testScenarios = data.table(read_excel(scenarioFile, skip = 1, col_types = "text"))
  colnames = unlist(unname(llply(names(testScenarios), function(x){str_replace_all(x, fixed(" "), "")})))
  setnames(testScenarios, colnames)
  
  # Get only the rows with numbers in TestID field
  testScenarios = testScenarios[grepl("\\d", TestID)]
  return(testScenarios)
}

```



```{r, results="hide"}

dataFolder = "~/Desktop/OptimalQuarantine/gaen-attenuation/data/Alpha Test Phase 1 Data/"
testerDirs = list.dirs(dataFolder, recursive = FALSE)

dt = NULL
for(testerDir in testerDirs){
  scenarioFile = list.files(testerDir, pattern = "\\.xlsx$", full.names = TRUE)[1]
  if(is.na(scenarioFile)){
    print(paste("No scenario file - skipping test directory: ", testerDir))
    print(paste(as.character(length(list.files(testerDir))), "Other files in the directory"))
    next
  }
  testScenarios = processScenarios(scenarioFile)
  setkey(testScenarios, by = TestID)
  
   for(file in list.files(testerDir)){
    if(grepl("json", file, fixed = TRUE)){
      newDt = processExposures(file.path(testerDir, file))
      testDesc = str_split(str_remove(file, ".json"), "_")[[1]]
      testID = testDesc[length(testDesc)]
      device = testDesc[2]
      tester = testDesc[1]
      
      newDt[, TestID := testID]
      newDt[, Device := device]
      newDt[, Tester := tester]
      
      setkey(newDt,by = TestID)
      newDt = merge(newDt, testScenarios, all.x = TRUE)

      
      
      if(is.null(dt)){
        dt = newDt
      }else{
        dt = rbind(dt, newDt, fill =TRUE)
      }
    }
  }

}

dt[, MeanAtten := 0.5*(MinThresh + MaxThresh)]
setnames(dt, "Distance(m)", "Distance")
dt[,Distance:=as.numeric((Distance))]
```

```{r}
dt[, Rep := floor(Duration/300)]

dtPoint = dt[Rep == 1]

for(rep in 2:max(dt$Rep)){
  dtPoint = rbind(dtPoint, do.call("rbind", replicate(rep, dt[Rep == rep], simplify = FALSE)))
}

ggplot(dtPoint, aes(y= Distance, x = MeanAtten, colour = Barrier)) + geom_jitter(height = 0.08, size = 2) + xlab("Attenuation [dB]") + ylab("Distance [m]") # + facet_wrap(~Device)
```

```{r}
dtPoint[, DistanceFactor := as.factor(Distance)]
dtPoint[,Barrier := as.factor(Barrier)]
model = lm(MeanAtten ~  Barrier + DistanceFactor + 0 , data= dtPoint)
print(model)
coefplot::coefplot(model)
```

```{r}
ggplot(dt) + geom_histogram( aes(x = TestID, y = Duration, fill = Tester), stat = "identity") + labs(x="Test ID")
```



```{r, include=FALSE}
dtSum = dt[,list(Duration = sum(Duration)), by = list(MinThresh, MaxThresh, Distance)]
dtSum[ ,MinDist := Distance -0.25]
dtSum[, MaxDist := Distance + 0.25]
dtSum[, Area := (MaxDist-MinDist)*(MaxThresh - MinThresh)]

ggplot(dtSum,aes(xmin=MinDist, xmax = MaxDist, ymin = MinThresh, ymax = MaxThresh)) + geom_rect(aes(fill = Duration/Area))

```
